version: '3'
services:
  frontend:
    build:
      context: ./snapurl-frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend

  backend:
    build:
      context: ./snapurl-backend
      dockerfile: Dockerfile
    ports:
      - 5000:3000
